### ISSUE TITLE
CT Volumes

### ISSUE THREAD

**Issue by dalbenzioG** [GLCUnet/dataset#2]
Hello, 

I was wondering if it is also possible to have the CT volumes of the segmentations.

Thank you in advance for any help you could provide.

**Comment by delton137** [comment]
As they explain in their paper (https://link.springer.com/chapter/10.1007/978-3-030-32692-0_32) , you can download the data from the Data Decathalon website: http://medicaldecathlon.com/ , https://drive.google.com/drive/folders/1HqEgzS8BV2c7xYNrZdEAnrHk7osJJ--2

It was mostly from the hepatic vessels challenge, if I recall correctly.

**Comment by dalbenzioG** [comment]
> As they explain in their paper (https://link.springer.com/chapter/10.1007/978-3-030-32692-0_32) , you can download the data from the Data Decathalon website: http://medicaldecathlon.com/ , https://drive.google.com/drive/folders/1HqEgzS8BV2c7xYNrZdEAnrHk7osJJ--2
> 
> It was mostly from the hepatic vessels challenge, if I recall correctly.
